#ifndef QTIDENTICON_GLOBAL_H
#define QTIDENTICON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTIDENTICON_LIBRARY)
#  define QTIDENTICONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTIDENTICONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTIDENTICON_GLOBAL_H
